services:
  sync:
    image: ayratbadykov/el_monitorro:0.2.3
    network_mode: host
    env_file: .env
    environment:
      BOT_BINARY: sync
      SYNC_INTERVAL_SECONDS: 300
      SYNC_WORKERS_NUMBER: 10
  deliver:
    image: ayratbadykov/el_monitorro:0.2.3
    network_mode: host
    env_file: .env
    environment:
      BOT_BINARY: deliver
      DELIVER_INTERVAL_SECONDS: 300
      DELIVER_WORKERS_NUMBER: 5
  commands:
    image: ayratbadykov/el_monitorro:0.2.3
    network_mode: host
    env_file: .env
    environment:
      BOT_BINARY: commands
